# Generated by Django 6.1.1 on 2026-09-24 05:39

import django.db.models.deletion
import reading.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('code', models.CharField(default=reading.models.new_case_code, max_length=16, unique=True)),
                ('image', models.CharField(max_length=200)),
                ('image_sha256', models.CharField(max_length=64)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('truth', models.CharField(max_length=50)),
                ('ai_answer', models.CharField(max_length=50)),
                ('ai_confidence', models.FloatField()),
                ('ai_box', models.JSONField(blank=True, null=True)),
                ('ai_planted', models.BooleanField()),
            ],
            options={
                'ordering': ['study', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('question', models.CharField(max_length=200)),
                ('choices', models.JSONField()),
                ('confidence_max', models.PositiveSmallIntegerField(default=5)),
                ('ai_source', models.CharField(default='AI model (simulated)', max_length=100)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed')], default='draft', max_length=10)),
                ('design_sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'studies',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consented_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='reading.study')),
            ],
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('alias', models.CharField(default=reading.models.new_alias, max_length=16, unique=True)),
                ('first_submission_id', models.CharField(default=reading.models.new_submission_id, max_length=16, unique=True)),
                ('final_submission_id', models.CharField(default=reading.models.new_submission_id, max_length=16, unique=True)),
                ('shown_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reading.case')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='reading.enrollment')),
            ],
            options={
                'ordering': ['enrollment', 'position'],
            },
        ),
        migrations.CreateModel(
            name='ImageAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=40)),
                ('allowed', models.BooleanField()),
                ('reason', models.CharField(blank=True, max_length=40)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('presentation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reading.presentation')),
            ],
            options={
                'verbose_name_plural': 'image accesses',
            },
        ),
        migrations.CreateModel(
            name='AIExposure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revealed_at', models.DateTimeField(auto_now_add=True)),
                ('presentation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_exposure', to='reading.presentation')),
            ],
        ),
        migrations.CreateModel(
            name='Read',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('first', 'First'), ('final', 'Final')], max_length=5)),
                ('answer', models.CharField(max_length=50)),
                ('confidence', models.PositiveSmallIntegerField()),
                ('client_submission_id', models.CharField(max_length=16, unique=True)),
                ('elapsed_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('committed_at', models.DateTimeField(auto_now_add=True)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='reading.presentation')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='reading.study'),
        ),
        migrations.AddConstraint(
            model_name='presentation',
            constraint=models.UniqueConstraint(fields=('enrollment', 'position'), name='one_presentation_per_position'),
        ),
        migrations.AddConstraint(
            model_name='read',
            constraint=models.UniqueConstraint(fields=('presentation', 'stage'), name='one_read_per_stage'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('user', 'study'), name='one_enrollment_per_study'),
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.UniqueConstraint(fields=('study', 'position'), name='one_case_per_position'),
        ),
    ]
