# Generated by Django 6.1.1 on 2026-09-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0003_reads_are_never_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='ai_slices',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='slices',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
